# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hijacker}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Woody Peterson"]
  s.date = %q{2009-11-18}
  s.description = %q{Allows a single Rails appliation to access many different databases}
  s.email = %q{woody@crystalcommerce.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "example_root_schema.rb",
     "init.rb",
     "install.rb",
     "lib/hijacker.rb",
     "lib/hijacker/active_record_ext.rb",
     "lib/hijacker/controller_methods.rb",
     "lib/hijacker/database.rb",
     "tasks/hijacker_tasks.rake",
     "uninstall.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{One application, multiple client databases}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/hijacker/database_spec.rb",
     "spec/hijacker_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

